# Generated by Django 5.2.1 on 2025-12-05 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_document_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='voice_auto_read',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
